
import React, { useState } from 'react';
import { Repository } from '../types';
import { GeminiService } from '../services/geminiService';
import { GitHubService } from '../services/githubService';
import { 
  FileText, 
  Sparkles, 
  Copy, 
  Check, 
  GitPullRequest,
  BookOpen,
  Scale,
  Shield,
  Clock,
  Map,
  Code,
  Bug,
  Lightbulb,
  RefreshCw,
  AlertCircle
} from 'lucide-react';

interface Props {
  repos: Repository[];
  githubService: GitHubService;
}

const Generator: React.FC<Props> = ({ repos, githubService }) => {
  const [selectedRepoName, setSelectedRepoName] = useState<string>('');
  const [fileType, setFileType] = useState<string>('README.md');
  const [loading, setLoading] = useState(false);
  const [prLoading, setPrLoading] = useState(false);
  const [output, setOutput] = useState<string>('');
  const [copied, setCopied] = useState(false);
  const [prResult, setPrResult] = useState<{ success: boolean; url?: string; error?: string } | null>(null);

  const fileTemplates = [
    { id: 'README.md', label: 'README.md', path: 'README.md', icon: <BookOpen className="w-4 h-4" />, color: 'text-indigo-400 bg-indigo-400/10' },
    { id: 'bug_report.md', label: 'Bug Report Template', path: '.github/ISSUE_TEMPLATE/bug_report.md', icon: <Bug className="w-4 h-4" />, color: 'text-orange-400 bg-orange-400/10' },
    { id: 'feature_request.md', label: 'Feature Request Template', path: '.github/ISSUE_TEMPLATE/feature_request.md', icon: <Lightbulb className="w-4 h-4" />, color: 'text-yellow-400 bg-yellow-400/10' },
    { id: 'CONTRIBUTING.md', label: 'CONTRIBUTING.md', path: 'CONTRIBUTING.md', icon: <Code className="w-4 h-4" />, color: 'text-green-400 bg-green-400/10' },
    { id: 'LICENSE', label: 'LICENSE', path: 'LICENSE', icon: <Scale className="w-4 h-4" />, color: 'text-yellow-400 bg-yellow-400/10' },
    { id: 'SECURITY.md', label: 'SECURITY.md', path: 'SECURITY.md', icon: <Shield className="w-4 h-4" />, color: 'text-red-400 bg-red-400/10' },
    { id: 'CHANGELOG.md', label: 'CHANGELOG.md', path: 'CHANGELOG.md', icon: <Clock className="w-4 h-4" />, color: 'text-blue-400 bg-blue-400/10' },
    { id: 'ARCHITECTURE.md', label: 'ARCHITECTURE.md', path: 'ARCHITECTURE.md', icon: <Map className="w-4 h-4" />, color: 'text-purple-400 bg-purple-400/10' },
  ];

  const handleGenerate = async () => {
    if (!selectedRepoName) return;
    setLoading(true);
    setPrResult(null);
    try {
      const repo = repos.find(r => r.name === selectedRepoName);
      const template = fileTemplates.find(t => t.id === fileType);
      const markdown = await GeminiService.generateMarkdown(
        template?.label || fileType,
        `Repo Name: ${repo?.name}, Language: ${repo?.language}, Desc: ${repo?.description}`,
        `Professional GitHub standard ${template?.label}. Use clean formatting and clear placeholders.`
      );
      setOutput(markdown);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleOpenPR = async () => {
    if (!selectedRepoName || !output) return;
    setPrLoading(true);
    setPrResult(null);
    try {
      const repo = repos.find(r => r.name === selectedRepoName);
      if (!repo) throw new Error("Repository not found");
      
      // Use full_name split to get owner and repo safely
      const [owner, repoName] = repo.full_name.split('/');
      const baseBranch = repo.default_branch;
      const template = fileTemplates.find(t => t.id === fileType);
      const filePath = template?.path || fileType;
      const newBranchName = `gitmomentum-improve-${Date.now()}`;
      
      // 1. Get default branch SHA
      const branchData = await githubService.getBranch(owner, repoName, baseBranch);
      const baseSha = branchData.commit.sha;

      // 2. Create new branch
      await githubService.createRef(owner, repoName, `refs/heads/${newBranchName}`, baseSha);
      
      // Small delay to allow GitHub internal state to catch up (prevents 404 on immediate PUT)
      await new Promise(resolve => setTimeout(resolve, 2000));

      // 3. Commit file (Check baseBranch for existing file SHA to avoid race conditions on the new branch)
      await githubService.writeFile(
        owner, 
        repoName, 
        filePath, 
        `docs: add ${template?.label || fileType} via GitMomentum`, 
        output, 
        newBranchName,
        baseBranch
      );

      // 4. Create PR
      const pr = await githubService.createPullRequest(
        owner,
        repoName,
        `Improvement: Add ${template?.label || fileType}`,
        newBranchName,
        baseBranch,
        `This PR adds a professionally generated ${template?.label || fileType} to improve the repository health and maintain meaningful streaks.\n\nGenerated by **GitMomentum**.`
      );

      setPrResult({ success: true, url: pr.html_url });
    } catch (err: any) {
      console.error("PR Error:", err);
      setPrResult({ success: false, error: err.message });
    } finally {
      setPrLoading(false);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
      {/* Settings */}
      <div className="space-y-6">
        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6">
          <h4 className="text-lg font-bold text-white mb-6">Markdown Suite</h4>
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-zinc-400 mb-2">Select Repository</label>
              <select 
                value={selectedRepoName}
                onChange={(e) => setSelectedRepoName(e.target.value)}
                className="w-full bg-zinc-800 border border-zinc-700 rounded-xl px-4 py-2.5 text-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
              >
                <option value="">Choose a repo...</option>
                {repos.map(r => <option key={r.id} value={r.name}>{r.name}</option>)}
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-zinc-400 mb-2">Template Type</label>
              <div className="grid grid-cols-1 gap-2 max-h-80 overflow-y-auto pr-2">
                {fileTemplates.map((t) => (
                  <button
                    key={t.id}
                    onClick={() => { setFileType(t.id); setPrResult(null); setOutput(''); }}
                    className={`flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-medium border text-left transition-all ${
                      fileType === t.id 
                        ? 'bg-zinc-800 border-indigo-500/50 text-white shadow-lg shadow-indigo-500/10' 
                        : 'bg-zinc-900 border-zinc-800 text-zinc-400 hover:text-white hover:border-zinc-700'
                    }`}
                  >
                    <div className={`p-1.5 rounded-lg shrink-0 ${t.color}`}>{t.icon}</div>
                    <span className="truncate">{t.label}</span>
                  </button>
                ))}
              </div>
            </div>

            <button
              onClick={handleGenerate}
              disabled={!selectedRepoName || loading}
              className="w-full mt-4 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed text-white font-bold py-3 rounded-xl transition-all flex items-center justify-center gap-2"
            >
              {loading ? (
                <RefreshCw className="w-5 h-5 animate-spin" />
              ) : (
                <Sparkles className="w-5 h-5" />
              )}
              Generate with AI
            </button>
          </div>
        </div>

        {prResult && (
          <div className={`p-4 rounded-xl border flex items-start gap-3 ${
            prResult.success 
              ? 'bg-green-500/10 border-green-500/20 text-green-400' 
              : 'bg-red-500/10 border-red-500/20 text-red-400'
          }`}>
            {prResult.success ? <Check className="w-5 h-5 shrink-0" /> : <AlertCircle className="w-5 h-5 shrink-0" />}
            <div className="min-w-0">
              <p className="text-sm font-bold">{prResult.success ? 'Pull Request Opened!' : 'PR Failed'}</p>
              {prResult.success ? (
                <a 
                  href={prResult.url} 
                  target="_blank" 
                  rel="noopener noreferrer" 
                  className="text-xs underline hover:text-green-300 transition-colors mt-1 inline-block"
                >
                  View on GitHub
                </a>
              ) : (
                <p className="text-xs mt-1 break-words">{prResult.error}</p>
              )}
            </div>
          </div>
        )}

        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6">
          <div className="flex items-center gap-3 text-zinc-400 mb-4">
            <Sparkles className="w-5 h-5 text-indigo-400" />
            <span className="text-sm font-bold">Best Practices</span>
          </div>
          <p className="text-xs text-zinc-500 leading-relaxed">
            Standard templates reduce friction for contributors. Adding Issue Templates helps automate triage and ensures you get high-quality feedback.
          </p>
        </div>
      </div>

      {/* Output Preview */}
      <div className="lg:col-span-2 space-y-4">
        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl overflow-hidden flex flex-col h-[700px]">
          <div className="bg-zinc-800/50 px-6 py-4 border-b border-zinc-800 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <FileText className="w-4 h-4 text-zinc-400" />
              <span className="text-sm font-mono text-zinc-300">
                {fileTemplates.find(t => t.id === fileType)?.path || fileType}
              </span>
            </div>
            <div className="flex items-center gap-2">
              <button 
                onClick={copyToClipboard}
                disabled={!output}
                className="p-2 hover:bg-zinc-700 rounded-lg text-zinc-400 hover:text-white transition-all disabled:opacity-0"
                title="Copy to clipboard"
              >
                {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
              </button>
              <button 
                onClick={handleOpenPR}
                disabled={!output || prLoading}
                className="flex items-center gap-2 px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold rounded-lg transition-all disabled:opacity-50"
              >
                {prLoading ? <RefreshCw className="w-3 h-3 animate-spin" /> : <GitPullRequest className="w-3 h-3" />}
                {prLoading ? 'Opening PR...' : 'Open PR'}
              </button>
            </div>
          </div>
          
          <div className="flex-1 overflow-auto p-8 bg-black/20">
            {output ? (
              <pre className="text-zinc-300 font-mono text-sm whitespace-pre-wrap leading-relaxed">
                {output}
              </pre>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-zinc-600 space-y-4">
                <FileText className="w-16 h-16 opacity-10" />
                <p className="text-sm font-medium">Select a repo and click Generate to see the magic.</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Generator;
